[API] Added Payment Controller and dtos
IvanZuravlev228/Car_Sharing_Service pull request #14
Opened 2023-06-01 13:27 UTC by outref

2023-06-01 14:04 UTC, OlehSarapuk requested changes

2023-06-01 14:04 UTC, OlehSarapuk commented on src/main/java/com/example/carsharingservice/repository/PaymentRepository.java
> +
double empty line

2023-06-01 14:04 UTC, OlehSarapuk commented on src/main/java/com/example/carsharingservice/repository/PaymentRepository.java
> +    List<Payment> findAllByRental_User_Id(Long userId);
very bad naming for method (we can not use _ )

2023-06-01 14:04 UTC, OlehSarapuk commented on src/main/java/com/example/carsharingservice/service/PaymentService.java
empty line

2023-06-01 14:04 UTC, OlehSarapuk commented on src/main/java/com/example/carsharingservice/controller/PaymentController.java
> +    public List<PaymentResponseDto> getPaymentsByUser(@RequestParam Long userId) {
it would be great to add pagination and swagger :)

2023-06-02 06:38 UTC, OlehSarapuk approved these changes

2023-06-02 06:45 UTC, IvanZuravlev228 approved these changes

2023-06-02 06:45 UTC, merged