Added rental entity
IvanZuravlev228/Car_Sharing_Service pull request #4
Opened 2023-05-29 12:49 UTC by KyrylH

2023-05-29 13:01 UTC, OlehSarapuk requested changes

2023-05-29 13:01 UTC, OlehSarapuk commented on src/main/java/com/example/carsharingservice/model/Rental.java
> +    @ManyToOne(fetch = FetchType.LAZY)
@JoinColumn with name car_id

2023-05-29 13:01 UTC, OlehSarapuk commented on src/main/java/com/example/carsharingservice/model/Rental.java
> +    private User user;
@joincolumn with name user_id

2023-05-29 13:01 UTC, OlehSarapuk commented on src/main/java/com/example/carsharingservice/model/Rental.java
> +    @ManyToOne(fetch = FetchType.LAZY)
@ToString.Exclude
    @EqualsAndHashCode.Exclude

2023-05-29 13:01 UTC, OlehSarapuk commented on src/main/java/com/example/carsharingservice/model/Rental.java
> +    private User user;
@ToString.Exclude
    @EqualsAndHashCode.Exclude

2023-05-29 13:47 UTC, IvanZuravlev228 approved these changes

2023-05-30 13:45 UTC, OlehSarapuk approved these changes

2023-05-30 13:46 UTC, merged