Telegrambot
IvanZuravlev228/Car_Sharing_Service pull request #7
Opened 2023-05-29 16:53 UTC by Nikitos787

2023-05-30 06:49 UTC, IvanZuravlev228 requested changes
You should fix your pull request, because you have problem with branch

2023-05-30 06:49 UTC, IvanZuravlev228 commented on .env
> +CHAT_ID=
empty line

2023-06-01 09:06 UTC, KyrylH approved these changes

2023-06-01 11:19 UTC, IvanZuravlev228 approved these changes

2023-06-01 11:20 UTC, merged